dist: xenial
language: python
python:
- '3.7'
install:
- pip install --upgrade --requirement requirements.txt
- pip install --upgrade --requirement test-requirements.txt
- pip install --upgrade git+ssh://git@github.com/threatgrid/softserve-atqc.git#egg=ctrlibrary
script:
- flake8 .
- coverage run --source api/ -m pytest --verbose tests/unit/ && coverage report
- pytest --verbose tests/functional/
